#!/bin/sh

if [ -z "$1" ]
  then
    echo "-------Enter a commit message-------"
    exit 1
  else
    echo "Staging all changes..."
    git add -A

    echo "Commiting to local branch..."
    git commit -m "$1"

    echo "Pushed to remote..."
    git push origin "$(git rev-parse --abbrev-ref HEAD)"
fi
