#!/bin/sh

commit_message=$1
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ -z "$1" ]
  then
    echo "-------Enter a commit message-------"
    exit 1
  else
    echo "Staging all changes..."
    git add -A

    echo "Commiting to local branch..."
    git commit -m "$commit_message"

    echo "Pushed to remote..."
    git push origin "$current_branch"
fi
